// Static ISO 3166-1 country reference data. Originally this was fetched live
// from restcountries.com, but that free/volunteer-run API intermittently
// returns non-array responses to requests from shared CI runner IPs (GitHub
// Actions, likely rate-limited or blocked as automated traffic) — this is
// permanent, essentially-never-changing reference data, so there's no real
// reason to depend on a live third-party call for it at all.
//
// Flag emoji is deliberately NOT stored here — it's computed from iso2 in
// flagEmoji() below, since a flag emoji is just two Unicode regional-
// indicator symbols derived mechanically from the two-letter code.

export type CountrySeed = { iso2: string; iso3: string; name: string; region: string };

export function flagEmoji(iso2: string): string {
  const codePoints = iso2
    .toUpperCase()
    .split("")
    .map((c) => 127397 + c.charCodeAt(0)); // regional indicator symbols start at U+1F1E6 for 'A' (0x41 + 127397 = 0x1F1E6)
  return String.fromCodePoint(...codePoints);
}

export const COUNTRIES: CountrySeed[] = [
  // Africa (54)
  { iso2: "DZ", iso3: "DZA", name: "Algeria", region: "Africa" },
  { iso2: "AO", iso3: "AGO", name: "Angola", region: "Africa" },
  { iso2: "BJ", iso3: "BEN", name: "Benin", region: "Africa" },
  { iso2: "BW", iso3: "BWA", name: "Botswana", region: "Africa" },
  { iso2: "BF", iso3: "BFA", name: "Burkina Faso", region: "Africa" },
  { iso2: "BI", iso3: "BDI", name: "Burundi", region: "Africa" },
  { iso2: "CV", iso3: "CPV", name: "Cabo Verde", region: "Africa" },
  { iso2: "CM", iso3: "CMR", name: "Cameroon", region: "Africa" },
  { iso2: "CF", iso3: "CAF", name: "Central African Republic", region: "Africa" },
  { iso2: "TD", iso3: "TCD", name: "Chad", region: "Africa" },
  { iso2: "KM", iso3: "COM", name: "Comoros", region: "Africa" },
  { iso2: "CG", iso3: "COG", name: "Republic of the Congo", region: "Africa" },
  { iso2: "CD", iso3: "COD", name: "DR Congo", region: "Africa" },
  { iso2: "DJ", iso3: "DJI", name: "Djibouti", region: "Africa" },
  { iso2: "EG", iso3: "EGY", name: "Egypt", region: "Africa" },
  { iso2: "GQ", iso3: "GNQ", name: "Equatorial Guinea", region: "Africa" },
  { iso2: "ER", iso3: "ERI", name: "Eritrea", region: "Africa" },
  { iso2: "SZ", iso3: "SWZ", name: "Eswatini", region: "Africa" },
  { iso2: "ET", iso3: "ETH", name: "Ethiopia", region: "Africa" },
  { iso2: "GA", iso3: "GAB", name: "Gabon", region: "Africa" },
  { iso2: "GM", iso3: "GMB", name: "Gambia", region: "Africa" },
  { iso2: "GH", iso3: "GHA", name: "Ghana", region: "Africa" },
  { iso2: "GN", iso3: "GIN", name: "Guinea", region: "Africa" },
  { iso2: "GW", iso3: "GNB", name: "Guinea-Bissau", region: "Africa" },
  { iso2: "CI", iso3: "CIV", name: "Ivory Coast", region: "Africa" },
  { iso2: "KE", iso3: "KEN", name: "Kenya", region: "Africa" },
  { iso2: "LS", iso3: "LSO", name: "Lesotho", region: "Africa" },
  { iso2: "LR", iso3: "LBR", name: "Liberia", region: "Africa" },
  { iso2: "LY", iso3: "LBY", name: "Libya", region: "Africa" },
  { iso2: "MG", iso3: "MDG", name: "Madagascar", region: "Africa" },
  { iso2: "MW", iso3: "MWI", name: "Malawi", region: "Africa" },
  { iso2: "ML", iso3: "MLI", name: "Mali", region: "Africa" },
  { iso2: "MR", iso3: "MRT", name: "Mauritania", region: "Africa" },
  { iso2: "MU", iso3: "MUS", name: "Mauritius", region: "Africa" },
  { iso2: "MA", iso3: "MAR", name: "Morocco", region: "Africa" },
  { iso2: "MZ", iso3: "MOZ", name: "Mozambique", region: "Africa" },
  { iso2: "NA", iso3: "NAM", name: "Namibia", region: "Africa" },
  { iso2: "NE", iso3: "NER", name: "Niger", region: "Africa" },
  { iso2: "NG", iso3: "NGA", name: "Nigeria", region: "Africa" },
  { iso2: "RW", iso3: "RWA", name: "Rwanda", region: "Africa" },
  { iso2: "ST", iso3: "STP", name: "Sao Tome and Principe", region: "Africa" },
  { iso2: "SN", iso3: "SEN", name: "Senegal", region: "Africa" },
  { iso2: "SC", iso3: "SYC", name: "Seychelles", region: "Africa" },
  { iso2: "SL", iso3: "SLE", name: "Sierra Leone", region: "Africa" },
  { iso2: "SO", iso3: "SOM", name: "Somalia", region: "Africa" },
  { iso2: "ZA", iso3: "ZAF", name: "South Africa", region: "Africa" },
  { iso2: "SS", iso3: "SSD", name: "South Sudan", region: "Africa" },
  { iso2: "SD", iso3: "SDN", name: "Sudan", region: "Africa" },
  { iso2: "TZ", iso3: "TZA", name: "Tanzania", region: "Africa" },
  { iso2: "TG", iso3: "TGO", name: "Togo", region: "Africa" },
  { iso2: "TN", iso3: "TUN", name: "Tunisia", region: "Africa" },
  { iso2: "UG", iso3: "UGA", name: "Uganda", region: "Africa" },
  { iso2: "ZM", iso3: "ZMB", name: "Zambia", region: "Africa" },
  { iso2: "ZW", iso3: "ZWE", name: "Zimbabwe", region: "Africa" },

  // Americas (35)
  { iso2: "AG", iso3: "ATG", name: "Antigua and Barbuda", region: "Americas" },
  { iso2: "AR", iso3: "ARG", name: "Argentina", region: "Americas" },
  { iso2: "BS", iso3: "BHS", name: "Bahamas", region: "Americas" },
  { iso2: "BB", iso3: "BRB", name: "Barbados", region: "Americas" },
  { iso2: "BZ", iso3: "BLZ", name: "Belize", region: "Americas" },
  { iso2: "BO", iso3: "BOL", name: "Bolivia", region: "Americas" },
  { iso2: "BR", iso3: "BRA", name: "Brazil", region: "Americas" },
  { iso2: "CA", iso3: "CAN", name: "Canada", region: "Americas" },
  { iso2: "CL", iso3: "CHL", name: "Chile", region: "Americas" },
  { iso2: "CO", iso3: "COL", name: "Colombia", region: "Americas" },
  { iso2: "CR", iso3: "CRI", name: "Costa Rica", region: "Americas" },
  { iso2: "CU", iso3: "CUB", name: "Cuba", region: "Americas" },
  { iso2: "DM", iso3: "DMA", name: "Dominica", region: "Americas" },
  { iso2: "DO", iso3: "DOM", name: "Dominican Republic", region: "Americas" },
  { iso2: "EC", iso3: "ECU", name: "Ecuador", region: "Americas" },
  { iso2: "SV", iso3: "SLV", name: "El Salvador", region: "Americas" },
  { iso2: "GD", iso3: "GRD", name: "Grenada", region: "Americas" },
  { iso2: "GT", iso3: "GTM", name: "Guatemala", region: "Americas" },
  { iso2: "GY", iso3: "GUY", name: "Guyana", region: "Americas" },
  { iso2: "HT", iso3: "HTI", name: "Haiti", region: "Americas" },
  { iso2: "HN", iso3: "HND", name: "Honduras", region: "Americas" },
  { iso2: "JM", iso3: "JAM", name: "Jamaica", region: "Americas" },
  { iso2: "MX", iso3: "MEX", name: "Mexico", region: "Americas" },
  { iso2: "NI", iso3: "NIC", name: "Nicaragua", region: "Americas" },
  { iso2: "PA", iso3: "PAN", name: "Panama", region: "Americas" },
  { iso2: "PY", iso3: "PRY", name: "Paraguay", region: "Americas" },
  { iso2: "PE", iso3: "PER", name: "Peru", region: "Americas" },
  { iso2: "KN", iso3: "KNA", name: "Saint Kitts and Nevis", region: "Americas" },
  { iso2: "LC", iso3: "LCA", name: "Saint Lucia", region: "Americas" },
  { iso2: "VC", iso3: "VCT", name: "Saint Vincent and the Grenadines", region: "Americas" },
  { iso2: "SR", iso3: "SUR", name: "Suriname", region: "Americas" },
  { iso2: "TT", iso3: "TTO", name: "Trinidad and Tobago", region: "Americas" },
  { iso2: "US", iso3: "USA", name: "United States", region: "Americas" },
  { iso2: "UY", iso3: "URY", name: "Uruguay", region: "Americas" },
  { iso2: "VE", iso3: "VEN", name: "Venezuela", region: "Americas" },

  // Asia (49)
  { iso2: "AF", iso3: "AFG", name: "Afghanistan", region: "Asia" },
  { iso2: "AM", iso3: "ARM", name: "Armenia", region: "Asia" },
  { iso2: "AZ", iso3: "AZE", name: "Azerbaijan", region: "Asia" },
  { iso2: "BH", iso3: "BHR", name: "Bahrain", region: "Asia" },
  { iso2: "BD", iso3: "BGD", name: "Bangladesh", region: "Asia" },
  { iso2: "BT", iso3: "BTN", name: "Bhutan", region: "Asia" },
  { iso2: "BN", iso3: "BRN", name: "Brunei", region: "Asia" },
  { iso2: "KH", iso3: "KHM", name: "Cambodia", region: "Asia" },
  { iso2: "CN", iso3: "CHN", name: "China", region: "Asia" },
  { iso2: "CY", iso3: "CYP", name: "Cyprus", region: "Asia" },
  { iso2: "GE", iso3: "GEO", name: "Georgia", region: "Asia" },
  { iso2: "IN", iso3: "IND", name: "India", region: "Asia" },
  { iso2: "ID", iso3: "IDN", name: "Indonesia", region: "Asia" },
  { iso2: "HK", iso3: "HKG", name: "Hong Kong", region: "Asia" },
  { iso2: "IR", iso3: "IRN", name: "Iran", region: "Asia" },
  { iso2: "IQ", iso3: "IRQ", name: "Iraq", region: "Asia" },
  { iso2: "IL", iso3: "ISR", name: "Israel", region: "Asia" },
  { iso2: "JP", iso3: "JPN", name: "Japan", region: "Asia" },
  { iso2: "JO", iso3: "JOR", name: "Jordan", region: "Asia" },
  { iso2: "KZ", iso3: "KAZ", name: "Kazakhstan", region: "Asia" },
  { iso2: "KW", iso3: "KWT", name: "Kuwait", region: "Asia" },
  { iso2: "KG", iso3: "KGZ", name: "Kyrgyzstan", region: "Asia" },
  { iso2: "LA", iso3: "LAO", name: "Laos", region: "Asia" },
  { iso2: "LB", iso3: "LBN", name: "Lebanon", region: "Asia" },
  { iso2: "MY", iso3: "MYS", name: "Malaysia", region: "Asia" },
  { iso2: "MV", iso3: "MDV", name: "Maldives", region: "Asia" },
  { iso2: "MN", iso3: "MNG", name: "Mongolia", region: "Asia" },
  { iso2: "MM", iso3: "MMR", name: "Myanmar", region: "Asia" },
  { iso2: "NP", iso3: "NPL", name: "Nepal", region: "Asia" },
  { iso2: "KP", iso3: "PRK", name: "North Korea", region: "Asia" },
  { iso2: "OM", iso3: "OMN", name: "Oman", region: "Asia" },
  { iso2: "PK", iso3: "PAK", name: "Pakistan", region: "Asia" },
  { iso2: "PS", iso3: "PSE", name: "Palestine", region: "Asia" },
  { iso2: "PH", iso3: "PHL", name: "Philippines", region: "Asia" },
  { iso2: "QA", iso3: "QAT", name: "Qatar", region: "Asia" },
  { iso2: "SA", iso3: "SAU", name: "Saudi Arabia", region: "Asia" },
  { iso2: "SG", iso3: "SGP", name: "Singapore", region: "Asia" },
  { iso2: "KR", iso3: "KOR", name: "South Korea", region: "Asia" },
  { iso2: "LK", iso3: "LKA", name: "Sri Lanka", region: "Asia" },
  { iso2: "SY", iso3: "SYR", name: "Syria", region: "Asia" },
  { iso2: "TW", iso3: "TWN", name: "Taiwan", region: "Asia" },
  { iso2: "TJ", iso3: "TJK", name: "Tajikistan", region: "Asia" },
  { iso2: "TH", iso3: "THA", name: "Thailand", region: "Asia" },
  { iso2: "TL", iso3: "TLS", name: "Timor-Leste", region: "Asia" },
  { iso2: "TR", iso3: "TUR", name: "Turkey", region: "Asia" },
  { iso2: "TM", iso3: "TKM", name: "Turkmenistan", region: "Asia" },
  { iso2: "AE", iso3: "ARE", name: "United Arab Emirates", region: "Asia" },
  { iso2: "UZ", iso3: "UZB", name: "Uzbekistan", region: "Asia" },
  { iso2: "VN", iso3: "VNM", name: "Vietnam", region: "Asia" },
  { iso2: "YE", iso3: "YEM", name: "Yemen", region: "Asia" },

  // Europe (44)
  { iso2: "AL", iso3: "ALB", name: "Albania", region: "Europe" },
  { iso2: "AD", iso3: "AND", name: "Andorra", region: "Europe" },
  { iso2: "AT", iso3: "AUT", name: "Austria", region: "Europe" },
  { iso2: "BY", iso3: "BLR", name: "Belarus", region: "Europe" },
  { iso2: "BE", iso3: "BEL", name: "Belgium", region: "Europe" },
  { iso2: "BA", iso3: "BIH", name: "Bosnia and Herzegovina", region: "Europe" },
  { iso2: "BG", iso3: "BGR", name: "Bulgaria", region: "Europe" },
  { iso2: "HR", iso3: "HRV", name: "Croatia", region: "Europe" },
  { iso2: "CZ", iso3: "CZE", name: "Czechia", region: "Europe" },
  { iso2: "DK", iso3: "DNK", name: "Denmark", region: "Europe" },
  { iso2: "EE", iso3: "EST", name: "Estonia", region: "Europe" },
  { iso2: "FI", iso3: "FIN", name: "Finland", region: "Europe" },
  { iso2: "FR", iso3: "FRA", name: "France", region: "Europe" },
  { iso2: "DE", iso3: "DEU", name: "Germany", region: "Europe" },
  { iso2: "GR", iso3: "GRC", name: "Greece", region: "Europe" },
  { iso2: "HU", iso3: "HUN", name: "Hungary", region: "Europe" },
  { iso2: "IS", iso3: "ISL", name: "Iceland", region: "Europe" },
  { iso2: "IE", iso3: "IRL", name: "Ireland", region: "Europe" },
  { iso2: "IT", iso3: "ITA", name: "Italy", region: "Europe" },
  { iso2: "LV", iso3: "LVA", name: "Latvia", region: "Europe" },
  { iso2: "LI", iso3: "LIE", name: "Liechtenstein", region: "Europe" },
  { iso2: "LT", iso3: "LTU", name: "Lithuania", region: "Europe" },
  { iso2: "LU", iso3: "LUX", name: "Luxembourg", region: "Europe" },
  { iso2: "MT", iso3: "MLT", name: "Malta", region: "Europe" },
  { iso2: "MD", iso3: "MDA", name: "Moldova", region: "Europe" },
  { iso2: "MC", iso3: "MCO", name: "Monaco", region: "Europe" },
  { iso2: "ME", iso3: "MNE", name: "Montenegro", region: "Europe" },
  { iso2: "NL", iso3: "NLD", name: "Netherlands", region: "Europe" },
  { iso2: "MK", iso3: "MKD", name: "North Macedonia", region: "Europe" },
  { iso2: "NO", iso3: "NOR", name: "Norway", region: "Europe" },
  { iso2: "PL", iso3: "POL", name: "Poland", region: "Europe" },
  { iso2: "PT", iso3: "PRT", name: "Portugal", region: "Europe" },
  { iso2: "RO", iso3: "ROU", name: "Romania", region: "Europe" },
  { iso2: "RU", iso3: "RUS", name: "Russia", region: "Europe" },
  { iso2: "SM", iso3: "SMR", name: "San Marino", region: "Europe" },
  { iso2: "RS", iso3: "SRB", name: "Serbia", region: "Europe" },
  { iso2: "SK", iso3: "SVK", name: "Slovakia", region: "Europe" },
  { iso2: "SI", iso3: "SVN", name: "Slovenia", region: "Europe" },
  { iso2: "ES", iso3: "ESP", name: "Spain", region: "Europe" },
  { iso2: "SE", iso3: "SWE", name: "Sweden", region: "Europe" },
  { iso2: "CH", iso3: "CHE", name: "Switzerland", region: "Europe" },
  { iso2: "UA", iso3: "UKR", name: "Ukraine", region: "Europe" },
  { iso2: "GB", iso3: "GBR", name: "United Kingdom", region: "Europe" },
  { iso2: "VA", iso3: "VAT", name: "Vatican City", region: "Europe" },

  // Oceania (14)
  { iso2: "AU", iso3: "AUS", name: "Australia", region: "Oceania" },
  { iso2: "FJ", iso3: "FJI", name: "Fiji", region: "Oceania" },
  { iso2: "KI", iso3: "KIR", name: "Kiribati", region: "Oceania" },
  { iso2: "MH", iso3: "MHL", name: "Marshall Islands", region: "Oceania" },
  { iso2: "FM", iso3: "FSM", name: "Micronesia", region: "Oceania" },
  { iso2: "NR", iso3: "NRU", name: "Nauru", region: "Oceania" },
  { iso2: "NZ", iso3: "NZL", name: "New Zealand", region: "Oceania" },
  { iso2: "PW", iso3: "PLW", name: "Palau", region: "Oceania" },
  { iso2: "PG", iso3: "PNG", name: "Papua New Guinea", region: "Oceania" },
  { iso2: "WS", iso3: "WSM", name: "Samoa", region: "Oceania" },
  { iso2: "SB", iso3: "SLB", name: "Solomon Islands", region: "Oceania" },
  { iso2: "TO", iso3: "TON", name: "Tonga", region: "Oceania" },
  { iso2: "TV", iso3: "TUV", name: "Tuvalu", region: "Oceania" },
  { iso2: "VU", iso3: "VUT", name: "Vanuatu", region: "Oceania" },
];
